CREATE TABLE IF NOT EXISTS whatsapp_instance (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  instance_name VARCHAR(100) NOT NULL UNIQUE,
  client_id VARCHAR(36) NULL,
  professional_id VARCHAR(36) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES client(id) ON DELETE SET NULL,
  FOREIGN KEY (professional_id) REFERENCES professional(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
